### PR TITLE
Decouple communication layer from Bukkit

### PR DESCRIPTION
**Pull request by erocs**
This pull was made to support creation of a business logic server to communicate with Mercury shards. Without this the communication layer would have been duplicated due to the missing Bukkit classes. Now this can be used as a Bukkit plugin or as an non-Bukkit API for communicating with the shards.

Compiles. Untested.

### CODE REVIEW

**Comment by rourke750** [comment]
Thx for this. Why is the jedis class did you make it j.close. won't that cause issues in other methods when it tries to get a resource but it can't because its closed?

**Comment by erocs** [comment]
Simple deprecation cleanup. Freeing the Jedis object via the JedisPool is deprecated. Jedis.close() is the way forward. If there are issues with a closed Jedis object elsewhere, then the class's logic was already flawed.

**Comment by rourke750** [comment]
@ProgrammerDan Can you handle this?

**Comment by rourke750** [comment]
Now everything will break

**Pull request merged**
